### ISSUE TITLE
The metadata in the annotation is empty

### ISSUE THREAD

**Issue by sun-0704** [fabiopoiesi/monet_dataset#2]
Can you tell me how to obtain multimodal metadata information? Thank you very much.

**Comment by sun-0704** [comment]
Some file annotations such as  runway_01 , lack metadata information.

**Comment by fabiopoiesi** [comment]
Unfortunately we had some corrupted bag files, and for some frames we could not extract the associated metadata.
This is just for few frames the others have it.
We will update the readme file mentioning this.
Thanks
